services:

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-sarca
    ports:
      - "8502:8502"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - rede_evolution  # Conecta na rede do outro projeto

networks:
  rede_evolution:
    external: true
    name: sintegra_docker-main_default  # Substitua pelo nome real